Import( 'env' )
Import( 'compmap' )

for subdir in [ 'rpHostCommonPlatformExe',
                'rpHCP_HostBasedSensor',
                'rpHCP_KernelAcquisition',
                'memory_loader_simulator' ]:
    SConscript(
            dirs = [ subdir ],
            file = 'SConscript',
            exports = dict( env = env.Clone(), compmap = compmap )
            )

# EOF
