Import( 'env' )
Import( 'compmap' )
for subdir in [
        'rpal',
        'CUnit-2.1-2/CUnit',
        'mbedtls',
        'cryptoLib',
        'obfuscationLib',
        'MemoryModule',
        'libb64',
        'zlib',
        'librpcm',
        'libOs',
        'rpHostCommonPlatformLib',
        'rpHostCommonPlatformIFaceLib',
        'notificationsLib',
        'processLib',
        'networkLib',
        'obsLib',
        'yara',
        'kernelAcquisitionLib',
        ]:
    SConscript(
            dirs = [ subdir ],
            file = 'SConscript',
            exports = dict( env = env.Clone(), compmap = compmap )
            )

# EOF
