Import( 'env' )
Import( 'compmap' )
import profiles

profiles.StaticLibrary(
        'rpHostCommonPlatformLib',
        profiles.ObfuscatedHeader(),
        profiles.RpalModule(),
        ).Target(
            env,
            Glob( '*.c' ),
            compmap,
            'cryptoLib', 'obfuscationLib', 'MemoryModule', 'b64', 'z', 'rpcm', 'Os', 'networkLib'
            )
# EOF
