#include "stateful_widgets.h"

static rpcm_tag root_file_path[] = {
    RP_TAGS_FILE_PATH,
    RPCM_END_TAG
};

StatefulWidget
    stateful_0_create
    (

    )
{
    return SAMTimeBurst( 10, 4,
#ifdef RPAL_PLATFORM_WINDOWS
                         SAMSimpleFilter( RP_TAGS_NOTIFICATION_NEW_PROCESS,
                                          RNATIVE_LITERAL( "*\\ipconfig.exe" ),
                                          0,
                                          RPCM_STRINGN,
                                          root_file_path,
                                          NULL ),
                         SAMSimpleFilter( RP_TAGS_NOTIFICATION_NEW_PROCESS,
                                          RNATIVE_LITERAL( "*\\apr.exe" ),
                                          0,
                                          RPCM_STRINGN,
                                          root_file_path,
                                          NULL ),
                         SAMSimpleFilter( RP_TAGS_NOTIFICATION_NEW_PROCESS,
                                          RNATIVE_LITERAL( "*\\route.exe" ),
                                          0,
                                          RPCM_STRINGN,
                                          root_file_path,
                                          NULL ),
                         SAMSimpleFilter( RP_TAGS_NOTIFICATION_NEW_PROCESS,
                                          RNATIVE_LITERAL( "*\\ping.exe" ),
                                          0,
                                          RPCM_STRINGN,
                                          root_file_path,
                                          NULL ),
                         SAMSimpleFilter( RP_TAGS_NOTIFICATION_NEW_PROCESS,
                                          RNATIVE_LITERAL( "*\\traceroute.exe" ),
                                          0,
                                          RPCM_STRINGN,
                                          root_file_path,
                                          NULL ),
                         SAMSimpleFilter( RP_TAGS_NOTIFICATION_NEW_PROCESS,
                                          RNATIVE_LITERAL( "*\\nslookup.exe" ),
                                          0,
                                          RPCM_STRINGN,
                                          root_file_path,
                                          NULL ),
                         SAMSimpleFilter( RP_TAGS_NOTIFICATION_NEW_PROCESS,
                                          RNATIVE_LITERAL( "*\\netstat.exe" ),
                                          0,
                                          RPCM_STRINGN,
                                          root_file_path,
                                          NULL ),
                         SAMSimpleFilter( RP_TAGS_NOTIFICATION_NEW_PROCESS,
                                          RNATIVE_LITERAL( "*\\wmic.exe" ),
                                          0,
                                          RPCM_STRINGN,
                                          root_file_path,
                                          NULL ),
                         SAMSimpleFilter( RP_TAGS_NOTIFICATION_NEW_PROCESS,
                                          RNATIVE_LITERAL( "*\\whoami.exe" ),
                                          0,
                                          RPCM_STRINGN,
                                          root_file_path,
                                          NULL ),
                         SAMSimpleFilter( RP_TAGS_NOTIFICATION_NEW_PROCESS,
                                          RNATIVE_LITERAL( "*\\systeminfo.exe" ),
                                          0,
                                          RPCM_STRINGN,
                                          root_file_path,
                                          NULL ),
                         SAMSimpleFilter( RP_TAGS_NOTIFICATION_NEW_PROCESS,
                                          RNATIVE_LITERAL( "*\\net?.exe" ),
                                          0,
                                          RPCM_STRINGN,
                                          root_file_path,
                                          NULL )
#elif defined(RPAL_PLATFORM_MACOSX)
        SAMSimpleFilter( RP_TAGS_NOTIFICATION_NEW_PROCESS,
                         RNATIVE_LITERAL( "*/ifconfig" ),
                         0,
                         RPCM_STRINGN,
                         root_file_path,
                         NULL ),
        SAMSimpleFilter( RP_TAGS_NOTIFICATION_NEW_PROCESS,
                         RNATIVE_LITERAL( "*/arp" ),
                         0,
                         RPCM_STRINGN,
                         root_file_path,
                         NULL ),
        SAMSimpleFilter( RP_TAGS_NOTIFICATION_NEW_PROCESS,
                         RNATIVE_LITERAL( "*/route" ),
                         0,
                         RPCM_STRINGN,
                         root_file_path,
                         NULL ),
        SAMSimpleFilter( RP_TAGS_NOTIFICATION_NEW_PROCESS,
                         RNATIVE_LITERAL( "*/ping" ),
                         0,
                         RPCM_STRINGN,
                         root_file_path,
                         NULL ),
        SAMSimpleFilter( RP_TAGS_NOTIFICATION_NEW_PROCESS,
                         RNATIVE_LITERAL( "*/traceroute" ),
                         0,
                         RPCM_STRINGN,
                         root_file_path,
                         NULL ),
        SAMSimpleFilter( RP_TAGS_NOTIFICATION_NEW_PROCESS,
                         RNATIVE_LITERAL( "*/nslookup" ),
                         0,
                         RPCM_STRINGN,
                         root_file_path,
                         NULL ),
        SAMSimpleFilter( RP_TAGS_NOTIFICATION_NEW_PROCESS,
                         RNATIVE_LITERAL( "*/netstat" ),
                         0,
                         RPCM_STRINGN,
                         root_file_path,
                         NULL )
#endif
                                          ,NULL );
}